app:
    resource: "@AppBundle/Controller/"
    type:     annotation

main_index:
    path: /
    defaults: { _controller: AppBundle:Main:index}

db_create:
    path: /create
    defaults: { _controller: AppBundle:Db:create}

db_show:
    path: /get/{productId}
    defaults: { _controller: AppBundle:Db:show}

db_update:
    path: /set/{productId}
    defaults: { _controller: AppBundle:Db:update}

db_remove:
    path: /remove/{productId}
    defaults: { _controller: AppBundle:Db:remove}

admin_index:
    path: /admin/{slug}
    defaults: { _controller: AppBundle:Admin:index}

admin_remove:
    path: /admin/remove/{productId}
    defaults: { _controller: AppBundle:Admin:remove}

admin_edit:
    path: /admin/edit/{productId}
    defaults: { _controller: AppBundle:Admin:edit}

admin_saveEdit:
    path: /admin/save
    defaults: { _controller: AppBundle:Admin:saveEdit}

captcha_routing:
    resource: "@CaptchaBundle/Resources/config/routing.yml"

user_logout:
    pattern:   /logout

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media