## To get started with security, check out the documentation:
## http://symfony.com/doc/current/book/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
#    providers:
#        in_memory:
#            memory: ~
    providers:
        our_db_provider:
            entity:
                class: AppBundle:User

    firewalls:
        main:
            pattern:    ^/
            http_basic: ~
            provider: our_db_provider

        default:
            anonymous: ~
    access_control:
#        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/admin, roles: ROLE_ADMIN }